!!python/object/new:zoedepth.utils.easydict.EasyDict
dictitems:
  attractor_alpha: 1000
  attractor_gamma: 2
  attractor_kind: mean
  attractor_type: inv
  aug: true
  baseline: true
  bin_centers_type: softplus
  bin_embedding_dim: 128
  clip_grad: 0.1
  condition: true
  dataset: nyu
  distributed: true
  do_resize: false
  force_keep_ar: true
  freeze: true
  g2l: true
  gpu: null
  img_size: &id001
  - 384
  - 512
  inverse_midas: false
  log_images_every: 0.2
  max_temp: 50.0
  max_translation: 100
  memory_efficient: true
  midas_model_type: DPT_BEiT_L_384
  min_temp: 0.0212
  model: zoedepth_custom
  n_attractors: &id002
  - 16
  - 8
  - 4
  - 1
  n_bins: 64
  name: PatchFusion
  notes: ''
  output_distribution: logbinomial
  prefetch: false
  pretrained_resource: ''
  print_losses: false
  project: ZoeDepth
  random_crop: false
  random_translate: false
  raw_depth_shape: &id003
  - 2160
  - 3840
  root: .
  sample_feat_level: 4
  sampled_training: false
  save_dir: ./nfs/monodepth3_checkpoints
  shared_dict: null
  sr_ratio: 1
  tags: ''
  train_midas: false
  transform_sample_gt_size: &id004
  - 2160
  - 3840
  translate_prob: 0.2
  uid: null
  use_amp: false
  use_area_prior: true
  use_fusion_network: true
  use_hr: false
  use_pretrained_midas: false
  use_shared_dict: false
  validate_every: 1
  version_name: patchfusion
  workers: 24
state:
  attractor_alpha: 1000
  attractor_gamma: 2
  attractor_kind: mean
  attractor_type: inv
  aug: true
  baseline: true
  bin_centers_type: softplus
  bin_embedding_dim: 128
  clip_grad: 0.1
  condition: true
  dataset: nyu
  distributed: true
  do_resize: false
  force_keep_ar: true
  freeze: true
  g2l: true
  gpu: null
  img_size: *id001
  inverse_midas: false
  log_images_every: 0.2
  max_temp: 50.0
  max_translation: 100
  memory_efficient: true
  midas_model_type: DPT_BEiT_L_384
  min_temp: 0.0212
  model: zoedepth_custom
  n_attractors: *id002
  n_bins: 64
  name: PatchFusion
  notes: ''
  output_distribution: logbinomial
  prefetch: false
  pretrained_resource: ''
  print_losses: false
  project: ZoeDepth
  random_crop: false
  random_translate: false
  raw_depth_shape: *id003
  root: .
  sample_feat_level: 4
  sampled_training: false
  save_dir: ./nfs/monodepth3_checkpoints
  shared_dict: null
  sr_ratio: 1
  tags: ''
  train_midas: false
  transform_sample_gt_size: *id004
  translate_prob: 0.2
  uid: null
  use_amp: false
  use_area_prior: true
  use_fusion_network: true
  use_hr: false
  use_pretrained_midas: false
  use_shared_dict: false
  validate_every: 1
  version_name: patchfusion
  workers: 24
